### ISSUE TITLE
list snapshots related only to certain instance

### ISSUE THREAD

**Issue by szilagyilaszlo** [jacksegal/google-compute-snapshot#3]
Firstly, many thanks for this work. Very useful script! :)

It could be an improvement (in the deleting process) if it lists only those snapshots which are related to a certain instance. So in line 30 I suggest using "--regexp" flag. 
For example "--regexp .*${DEVICE_NAME}.*" 

However, this solution suggested by me is not the best one: if you have instances named like "test", "test01", "testmachine", because if you run the script on "test" it will delete all snapshots containing "test" expression.

Maybe we can use the unique ID of the instance in the snapshot name: $(curl -s "http://metadata.google.internal/computeMetadata/v1/instance/id" -H "Metadata-Flavor: Google"). I think this can ensure that only those snapshots will be deleted which are related to a certain instance.

**Comment by jacksegal** [comment]
Thanks - great suggestion! 

Using the regex flag, I've just committed a change that only deletes snapshots that:

1. Are for the VM that the script is running on
2. That were created by the script

This means that it won't delete the existing snapshots created in the last 7 days (when they become "expired"), because the existing snapshots do not meet the new criteria.

I suggest manually deleting them in 10 days time.
