### ISSUE TITLE
which snapshot will be used when restore the server

### ISSUE THREAD

**Issue by mshanak** [jacksegal/google-compute-snapshot#40]
hello

I wonder which one of the snapshots will be used when restoring the server. I run the script and after a while, the script created many snapshots with deferent sizes, the first one was 2.5G but the others have about 60mb and less.
which one of the snapshots I can use to restore the server.

regards

**Comment by jacksegal** [comment]
Hi @mshanak,

You can use whichever snapshot you want.

Google cloud takes incremental snapshots, which is why the subsequent backups are smaller.  When restoring, it loads the full backup snapshot first (2.5G) and then the incremental snapshots (< 60mb).

If you ever delete the full backup snapshot, it moves the full backup to the next snapshot automatically. Official documentation has a diagram that can explain it better than me: https://cloud.google.com/compute/docs/disks/create-snapshots

Cheers,
Jack
